# Generated by Django 3.2.13 on 2022-07-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponrating',
            name='profile',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/brands/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profiles/'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/weapons/'),
        ),
    ]
