# Generated by Django 3.2.13 on 2022-07-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220703_0147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
