# Generated by Django 4.2.7 on 2024-08-23 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_code_confirm_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='patent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_user', to='api.patent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_user', to='api.team'),
        ),
    ]
